# Generated by Django 4.2 on 2023-06-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('email', models.CharField(db_column='Email', max_length=50, unique=True)),
                ('password', models.CharField(db_column='Password', max_length=50)),
                ('name', models.CharField(db_collation='utf8mb4_bin', db_column='Name', max_length=50)),
                ('license', models.CharField(db_column='License', max_length=10, unique=True)),
                ('isAdmin', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'account',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('isfree', models.IntegerField(db_column='IsFree')),
            ],
            options={
                'db_table': 'parkinglot',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('license', models.CharField(db_column='License', max_length=10)),
                ('timein', models.DateTimeField(db_column='TimeIn')),
                ('timeout', models.DateTimeField(blank=True, db_column='TimeOut', null=True)),
                ('total', models.DecimalField(blank=True, db_column='Total', decimal_places=3, max_digits=18, null=True)),
                ('ispaid', models.IntegerField(db_column='IsPaid')),
            ],
            options={
                'db_table': 'ticket',
                'ordering': ['id'],
                'managed': False,
            },
        ),
    ]
