# Generated by Django 4.2 on 2023-06-02 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'managed': False, 'ordering': ['id_account']},
        ),
    ]
