# Generated by Django 4.2 on 2023-06-04 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_account_options_alter_ticket_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'managed': False, 'ordering': ['account_id']},
        ),
    ]
