version: '3'
services:
  app:
    build: .
    volumes:
      - .:/django
    ports:
      - 8000:8000
    image: app:django
    container_name: server
    command: daphne --bind 0.0.0.0:8000 server.asgi:application
